# Generated by Django 5.2 on 2025-06-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intruments', '0002_item_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='serial_number',
            field=models.CharField(max_length=100),
        ),
    ]
