# Generated by Django 5.2 on 2025-06-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intruments', '0004_item_unique_item_group'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='unique_item_group',
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('serial_number', 'bill_number'), name='unique_item_group'),
        ),
    ]
