# Generated by Django 5.2 on 2025-06-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intruments', '0006_item_category'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='unique_item_group',
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('category', 'serial_number', 'bill_number'), name='unique_item_group'),
        ),
    ]
