# Generated by Django 5.2 on 2025-07-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_customuser_username_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
