# Generated by Django 5.2 on 2025-07-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_uploadedfile_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='cdn_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
