# Generated by Django 5.2.4 on 2025-10-13 12:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_uploadedfile_cdn_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='department',
            new_name='branch',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='customuser',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lab_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='customuser',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='lab_days',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='lab_days',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='lab_day',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='year',
            field=models.CharField(default=22, max_length=10),
            preserve_default=False,
        ),
    ]
