# Generated by Django 5.2.4 on 2025-10-13 19:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_department_studentprofile_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='lab_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=15), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='lab_day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=20),
        ),
    ]
