# Generated by Django 5.2.4 on 2025-10-13 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_customuser_lab_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.department'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.department'),
        ),
    ]
