# Generated by Django 5.2.4 on 2025-10-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_department_alter_facultyprofile_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('CCE', 'CCE'), ('ECE', 'ECE'), ('ME', 'ME'), ('PHY', 'PHY'), ('HSS', 'HSS')], max_length=10),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('CCE', 'CCE'), ('ECE', 'ECE'), ('ME', 'ME'), ('PHY', 'PHY'), ('HSS', 'HSS')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
