# Generated by Django 5.2.4 on 2025-10-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='financial_year',
            field=models.CharField(blank=True, db_index=True, max_length=9),
        ),
    ]
