# Generated by Django 5.2.4 on 2025-10-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_bill_financial_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
