# Generated by Django 5.2.4 on 2025-11-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_bill_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
