# Generated by Django 5.2.4 on 2025-11-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_lab_handout'),
    ]

    operations = [
        migrations.AddField(
            model_name='handout',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
