# Generated by Django 5.2 on 2025-06-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intruments', '0003_alter_item_serial_number'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('serial_number', 'bill_number', 'purchase_date'), name='unique_item_group'),
        ),
    ]
