# Generated by Django 5.2 on 2025-06-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intruments', '0005_remove_item_unique_item_group_item_unique_item_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('resistors', 'Resistors'), ('ics', 'ICs'), ('capacitors', 'Capacitors')], default='resistors', max_length=25),
        ),
    ]
