# Generated by Django 5.2.4 on 2025-10-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intruments', '0009_issuerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuerequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuerequest',
            name='return_by',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
