# Generated by Django 5.2.4 on 2025-10-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intruments', '0010_issuerequest_approved_at_issuerequest_return_by'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='unique_item_group',
        ),
        migrations.RemoveField(
            model_name='item',
            name='bill_number',
        ),
        migrations.RemoveField(
            model_name='item',
            name='buyer_email',
        ),
        migrations.RemoveField(
            model_name='item',
            name='buyer_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='item',
            name='gst_number',
        ),
        migrations.RemoveField(
            model_name='item',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_consumable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='item',
            name='max_issue_limit',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='min_issue_limit',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
