# Generated by Django 5.2.4 on 2025-10-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intruments', '0011_remove_item_unique_item_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_available',
            field=models.BooleanField(default=True, help_text='If false, item is not available for issue/requests'),
        ),
    ]
