# Generated by Django 5.2.4 on 2025-11-12 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intruments', '0002_issue_messages_and_submission'),
        ('intruments', '0012_item_is_available'),
    ]

    operations = [
    ]
