# Generated by Django 5.2.4 on 2025-11-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intruments', '0013_merge_20251113_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuemessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
