# Generated by Django 5.2 on 2025-06-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('faculty', 'Faculty'), ('staff', 'Staff')], default='student', max_length=10),
        ),
    ]
